apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 600Mi
          workingDir: /workspace/source
        steps:
        - image: ghcr.io/jenkins-x/jx-boot:3.2.22
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - image: golang:1.15
          name: build-make-linux
          resources: {}
          script: |
            #!/bin/sh
            make linux
        - image: gcr.io/jenkinsxio/jx-registry:0.0.12
          name: check-registry
        - image: gcr.io/kaniko-project/executor:debug-v1.3.0
          name: build-container-build
          resources: {}
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
            
            cat Dockerfile|grep -i from|grep -i " as " "awk '{print $NF}'|\
                xargs -n 1 -I {} sh -c "echo 'pulling $BRANCH_NAME-{}' && /kaniko/warmer --image=$PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$BRANCH_NAME-{}"
  
            cat Dockerfile |grep -i from | grep -i " as " | awk '{print $NF}' |\
                xargs -n 1 -I {} sh -c "/kaniko/executor $KANIKO_FLAGS \
                                    --build-arg=DOCKER_REGISTRY=$DOCKER_REGISTRY/jx \
                                    --target {} \
                                    --cache=true \
                                    --cache-repo=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME \
                                    --context=/workspace/source \
                                    --dockerfile=Dockerfile \
                                    --destination=$PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$BRANCH_NAME-{}"
        - image: ghcr.io/jenkins-x/jx-preview:0.0.171
          name: promote-jx-preview
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh
            jx preview create
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 20m0s
status: {}
